services:

  web2:
    build:
      context: ./project2/
    command: gunicorn project2.wsgi:application --bind 0.0.0.0:3000
    volumes:
      - ./project2/:/usr/src/app/
      - static_files2:/usr/src/app/staticfiles
    expose:
      - 3000

volumes:
  static_files2:

